server:
  port: 9102

spring:
  application:
    name: api-user-regist
  redis:
    host: 192.168.153.130
    port: 6379
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://rainlu:123456@localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ConnectTimeout: 1000
  MaxAutoRetries: 2
  ReadTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000